/* eslint-disable */
/* tslint:disable */
/**
 * This is an autogenerated file created by the Stencil compiler.
 * It contains typing information for all components that exist in this project.
 */
import { HTMLStencilElement, JSXBase } from "@stencil/core/internal";
export namespace Components {
    interface Nemo260AmbulanceWlList {
    }
}
declare global {
    interface HTMLNemo260AmbulanceWlListElement extends Components.Nemo260AmbulanceWlList, HTMLStencilElement {
    }
    var HTMLNemo260AmbulanceWlListElement: {
        prototype: HTMLNemo260AmbulanceWlListElement;
        new (): HTMLNemo260AmbulanceWlListElement;
    };
    interface HTMLElementTagNameMap {
        "nemo260-ambulance-wl-list": HTMLNemo260AmbulanceWlListElement;
    }
}
declare namespace LocalJSX {
    interface Nemo260AmbulanceWlList {
    }
    interface IntrinsicElements {
        "nemo260-ambulance-wl-list": Nemo260AmbulanceWlList;
    }
}
export { LocalJSX as JSX };
declare module "@stencil/core" {
    export namespace JSX {
        interface IntrinsicElements {
            "nemo260-ambulance-wl-list": LocalJSX.Nemo260AmbulanceWlList & JSXBase.HTMLAttributes<HTMLNemo260AmbulanceWlListElement>;
        }
    }
}
